### ISSUE TITLE
docker-broker-images/1 failed to upload

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-community/docker-services-boshworkspace#33]
@rkoster 

I added the offline pieces to my `deployments/docker-aws-vpc.yml` file but get a blobstore error during `bosh prepare deployment`:

```
Uploading 'docker-broker-images/1'
Acting as user 'admin' on 'bosh-vpc-3854145d'
Downloading from blobstore (id=2f86ba39-d462-41b9-bc94-e6a55801687a)...
Blobstore error: Could not fetch object, 403/
```

My changes to deployment file included:

```
releases:
- name: docker
  version: '17'
  git: https://github.com/cf-platform-eng/docker-boshrelease.git
- name: docker-broker-images
  version: '1'
  git: https://github.com/cloudfoundry-community/docker-broker-images-boshrelease.git
stemcells:
- name: bosh-aws-xen-ubuntu-trusty-go_agent
  version: 2941
templates:
- docker-deployment.yml
- docker-jobs.yml
- docker-properties.yml
- docker-offline.yml
- docker-aws-vpc.yml
```
